In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [9]:
print(x_data)
print(x_data.shape)
print(x_data[1])
print(x_data[1][1])
print(x_data[1][1].item())  # item()은 scalar로 만드는 함수

tensor([[1, 2],
        [3, 4]])
torch.Size([2, 2])
tensor([3, 4])
tensor(4)
4


In [11]:
x = torch.randn(2, 2)   # 
print(x)

tensor([[ 0.8485, -0.4339],
        [ 0.1641, -0.0597]])


In [13]:
print(x[0])
y = x[0]    # 주소 복사 (좀 더 공부하기)
y = x[0].detach().clone()   # 깊은 복사, 얕은 복사로 주소를 복사하는 것이 아닌 것?
print(y)

tensor([ 0.8485, -0.4339])
tensor([ 0.8485, -0.4339])


In [14]:
y = 0
print(x[0])
print(y)

tensor([ 0.8485, -0.4339])
0
